name: Digital Flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-openlane:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          python3-pip \
          tcl-dev \
          swig \
          cmake 

      - name: Install Python dSependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r Dependencies/requirements_python.txt

      - name: Clone OpenLane repository
        run: |
          git clone https://github.com/The-OpenROAD-Project/OpenLane.git
          cd OpenLane
          make pull-openlane

      - name: Set up OpenLane environment
        run: |
          cd OpenLane
          make

      - name: Test Openlane
        run: |
          cd OpenLane
          make test

      - name: Save OpenLane setup
        uses: actions/upload-artifact@v3
        with:
          name: openlane-setup
          path: OpenLane/


  run-openlane:
    needs: setup-openlane
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download OpenLane setup
        uses: actions/download-artifact@v3
        with:
          name: openlane-setup
          path: OpenLane/

      - name: Run OpenLane Flow
        run: |
          cd OpenLane
          docker run --rm -v $(pwd)/Design:/work/designs/Design -w /work \
          theopenroad/openlane:latest \
          flow.tcl -design Design

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: openlane-results
          path: OpenLane/runs/
