name: Digital Flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-openlane:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          python3-pip \
          tcl-dev \
          swig \
          cmake 

      - name: Install Python Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r Dependencies/requirements_python.txt

      - name: Clone OpenLane repository
        run: |
          git clone https://github.com/The-OpenROAD-Project/OpenLane.git
          cd OpenLane
          make pull-openlane

      - name: Set up OpenLane environment
        run: |
          cd OpenLane
          make

      - name: Test Openlane
        run: |
          cd OpenLane
          make test

      - name: Compress OpenLane setup
        run: |
          tar -czf openlane-setup.tar.gz OpenLane
        
      - name: Save OpenLane setup
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: openlane-setup
          path: openlane-setup.tar.gz


  run-openlane:
    needs: setup-openlane
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download OpenLane setup
        uses: actions/download-artifact@v4
        with:
          name: openlane-setup
          path: OpenLane/

      - name: Extract OpenLane setup
        run: |
          tar -xzf OpenLane/openlane-setup.tar.gz -C OpenLane

      - name: Run OpenLane Flow
        run: |
          set -e  # Habilita el modo de salida inmediata en caso de error
          cd OpenLane
          docker run --rm -v $(pwd)/Project:/work/designs/Project -w /work efabless/openlane flow.tcl -design Project
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: openlane-results
          path: OpenLane/runs/
